# Generated by Django 4.2.11 on 2024-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='named_url',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Именованный URL'),
        ),
    ]
